#!/bin/bash


# Get DTP and set containers to an array
POD="$(kubectl get pods | grep dtp | grep Running | awk '{print $1}')"
ARRAY=($(kubectl get pods ${POD} -o jsonpath='{.spec.containers[*].name}'))
POSSIBLE=(dtp-base dtp-gcp dtp-irods dtp-aws dtp-minio dtp-ndn dtp-aspera dtp-sra-toolkit dtp-globus)

POSITIONAL=()
while [[ $# -gt 0 ]]
do
KEY="$1"

case $KEY in
    -h|--help)
    echo "--------------------"
    echo "- BACKGROUND MODE -"
    echo "--------------------"
    echo "Description: Background Mode is a way to pass commands to DTP containers without interactively entering the container."
    echo "Usage: ./background <--container1> 'command1' <--container2> 'command2' .... <--containerN> 'commandN'"
    echo "Possible: ${POSSIBLE[@]}"
    echo "Running: ${ARRAY[@]}"
    echo "--------------------"
    shift # past argument
    shift # past value
    ;;
    --dtp-*)
    CONTAINER=${KEY#"--"}
    if [[ " ${ARRAY[*]} " == *" ${CONTAINER} "* ]]; then
        echo "Executing $2 in ${CONTAINER}...."
        kubectl exec -it ${POD} --container ${CONTAINER} -- $2
    elif [[ " ${POSSIBLE[*]} " == *" ${CONTAINER} "* ]]; then
        echo "Container ${CONTAINER} not found! Are you sure it is deployed?"
    else
        echo "Container ${CONTAINER} is not one of the possible options! Are you sure it is spelled correctly?"
        echo "Possible: ${POSSIBLE[@]}"
    fi
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    echo "Unknown option: $1"
    echo "Use -h/--help for assistance."
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters
