#!/bin/bash


if [[ $# != 1 ]]; then
	echo "usage: $0 <filename>"
	exit -1
fi

# Get config

source $1

# iRODS

export IRODS_ENV=$(cat ${IRODS_ENV_FILE_PATH} | base64 | tr -d '\n')

cat > helm/templates/irods-secret.yaml <<EOF
{{ if .Values.iRODS.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: irods
type: Opaque
stringData:
    IRODS_PASSWORD: ${IRODS_PASS}
    IRODS_ENVIRONMENT_FILE: /etc/.irods/irods_environment.json
data:
  irods_environment.json: ${IRODS_ENV}
{{ end }}
EOF

echo "iRODS"
echo " "
cat helm/templates/irods-secret.yaml
echo " "

# AWS

cat > helm/templates/aws-secret.yaml <<EOF
{{ if .Values.AWS.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
{{ end }}
EOF

echo "AWS-CLI"
echo " "
cat helm/templates/aws-secret.yaml
echo " "

# Aspera

cat > helm/templates/aspera-secret.yaml <<EOF
{{ if .Values.Aspera.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: aspera
type: Opaque
stringData:
    ACLI_USERNAME: ${ACLI_USER}
    ACLI_PASSWORD: ${ACLI_PASS}
{{ end }}
EOF

echo "Aspera"
echo " "
cat helm/templates/aspera-secret.yaml
echo " "

# Globus

cat > helm/templates/globus-secret.yaml <<EOF
{{ if .Values.Globus.Secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: globus
type: Opaque
stringData:
    SETUP_KEY: ${GLOBUS_KEY}
{{ end }}
EOF

echo "Globus"
echo " "
cat helm/templates/globus-secret.yaml
echo " "
